networks:
  moor_net:

services:
  moor-daemon:
    image: ghcr.io/rdaum/moor:release
    build:
      context: ..
      network: host
    container_name: "cowbell-moor-daemon"
    environment:
      - RUST_BACKTRACE=1
    working_dir: /moor
    # Keep the database on the host, not in our container
    volumes:
      - ./:/db
    command: >
      /moor/moor-daemon /db/cowbell.db
        --rpc-listen=tcp://0.0.0.0:7899 
        --events-listen=tcp://0.0.0.0:7898 
        --workers-response-listen=tcp://0.0.0.0:7897 
        --workers-request-listen=tcp://0.0.0.0:7896 
        --import=/db/src --import-format=objdef
        --export=/db/objdump-out --export-format objdef 
        --checkpoint-interval-seconds=360
        --custom-errors true
    ports:
      # ZMQ ports
      - "7899:7899" # RPC listener
      - "7898:7898" # Events listener
      - "7897:7897" # Workers response listener
      - "7896:7896" # Workers request listener      # ZMQ ports
    networks:
      - moor_net

  moor-telnet-host:
    image: ghcr.io/rdaum/moor:release
    build:
      context: ..
      network: host
    container_name: "cowbell-moor-telnet-host"
    environment:
      - RUST_BACKTRACE=1
    working_dir: /moor
    command: >
      /moor/moor-telnet-host --telnet-address=0.0.0.0 
        --telnet-port=8888 
        --rpc-address=tcp://moor-daemon:7899 
        --events-address=tcp://moor-daemon:7898
    ports:
      # Telnet listener
      - "8888:8888"
    networks:
      - moor_net

  moor-web-host:
    image: ghcr.io/rdaum/moor:release
    build:
      context: ..
      network: host
    container_name: "cowbell-moor-web-host"
    environment:
      - RUST_BACKTRACE=1
    working_dir: /moor
    command: >
      /moor/moor-web-host 
        --listen-address=0.0.0.0:8081
        --rpc-address=tcp://moor-daemon:7899 
        --events-address=tcp://moor-daemon:7898
    ports:
      # API listener (internal)
      - "8081:8081"
    networks:
      - moor_net

  # Frontend web server that serves static files and proxies API calls
  moor-frontend:
    image: ghcr.io/rdaum/moor:frontend
    build:
      context: ..
      target: frontend
      network: host
    container_name: "moor-frontend"
    depends_on:
      - moor-web-host
    ports:
      # Main web interface
      - "8080:80"
    networks:
      - moor_net
