name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run textdump build
      run: make gen.moo-textdump

    - name: Run objdef dir build
      run: make gen.objdir
      
    - name: Rebuild then check for changes
      id: check_changes
      run: |
         make rebuild
         if [[ -n $(git status --porcelain) ]]; then
             echo "changes=true" >> "$GITHUB_OUTPUT"; 
         fi
      
